version: 0.2

env:
  variables:
    AWS_REGION: "ap-south-1"
    AWS_ACCOUNT_ID: "904233129662"
    ECR_REPO_NAME: "repo_ecs"
    IMAGE_TAG: "latest" 

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo "Setting IMAGE_URI..."
      - IMAGE_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG"
      - echo "IMAGE_URI: $IMAGE_URI"
      - echo "Checking Docker version..."
      - docker --version

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t "$IMAGE_URI" .
      - echo "Docker build completed."

  post_build:
    commands:
      - echo "Pushing the image to ECR..."
      - docker push "$IMAGE_URI"
      - echo "Docker image pushed successfully."
