version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to ECR...
      - CODEBUILD_RESOLVED_SOURCE_VERSION="$(CODEBUILD_RESOLVED_SOURCE_VERSION:-$IMAGE_TAG)"
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo image_tag $IMAGE_TAG
      - REPO="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
      - IMAGE_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG"
      - echo Repository $REPO
      - docker login -u AWS -p $(aws ecr get-login-password --region $AWS_DEFAULT_REGION) $REPO

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t "$IMAGE_URI" .

  post_build:
    commands:
      - echo Build completed on `date`
      - bash -c "if ["$CODEBUILD_BUILD_SUCCEEDING" = "0" ]; then exit 1; fi"
      - echo Pushing the docker image
      - docker push $IMAGE_URI
      - echo Writing image definitions file...

